### ISSUE TITLE
Source code does not seem to match version in Zimbra.org

### ISSUE THREAD

**Issue by ghost** [xMAnton/ADPassword#11]
Looking at the Binary file from here:
https://zimbra.org/extend/items/view/adpassword
Looking into the binaries I see:
ADPassword->com/zimbra/adPassword/ADChangePasswordListener-> com/zimbra/adPassword/ADPassword

I just build the sources from this github, they throw the following error on Zimbra:
com.zimbra.common.soap.SoapFaultException: system failure: change password listener ADPassword for account test@barrydegraaff.tk not found

Looking into the fresh binary I see:
ADPassword->it/iknowconsulting/adpassword/ADChangePasswordListener->it/iknowconsulting/adpassword/ADPassword

@xMAnton Maybe I am missing something and building it wrong? Should the Github source be the same as the version found in Zimbra.org?

**Comment by ghost** [comment]
The source from github shows in the log:

**Comment by ghost** [comment]
2016-04-03 10:06:54,561 WARN  [main] [] extensions - no Zimbra-Extension-Class found, ignored: /opt/zimbra/lib/ext/adpassword

**Comment by ghost** [comment]
seems like 
META-INF/MANIFEST.MF
is not added correctly by netbeans, the line:
Zimbra-Extension-Class: com.zimbra.adpassword.ADPassword
or so should be added...

but then still the version on .org is NOT the same as on github, and seems like the builded code does not work..

**Comment by ghost** [comment]
Yes, was able to build a working jar from the code in this repo, it turns out, netbeans removing the line from META-INF/MANIFEST.MF was the issue. So I love this repo!

**Comment by xMAnton** [comment]
So you solved. Great.

Please note that it's been a while since I've switched to Eclipse!
