### ISSUE TITLE
Modify updatePassword

### ISSUE THREAD

**Issue by ronaldomaya** [xMAnton/ADPassword#3]
função updatePassword modificada para localizar usuários em qualquer Unidade Organizacional

public void updatePassword(String username, String password) throws NamingException {
        NamingEnumeration userfield;
        String quotedPassword = "\"" + password + "\"";
        char unicodePwd[] = quotedPassword.toCharArray();
        byte pwdArray[] = new byte[unicodePwd.length \* 2];
        for (int i=0; i<unicodePwd.length; i++) {
            pwdArray[i*2 + 1] = (byte) (unicodePwd[i] >>> 8);
            pwdArray[i*2 + 0] = (byte) (unicodePwd[i] & 0xff);
        }
        ModificationItem[] mods = new ModificationItem[1];
        mods[0] = new ModificationItem(DirContext.REPLACE_ATTRIBUTE, new BasicAttribute("UnicodePwd", pwdArray));

```
    //ldapContext.modifyAttributes("cn=" + username + "," + authLdapSearchBase, mods);

    NamingEnumeration users = fetchUser(username);

    SearchResult user = (SearchResult)users.nextElement();
    String RDN = user.getNameInNamespace();

    ldapContext.modifyAttributes(RDN, mods);
}
```

---

in ADChangePasswordListener modify acct.getDisplayName() by acct.getUid()

 //adc.updatePassword(acct.getDisplayName() , newPassword);
  adc.updatePassword(acct.getUid(), newPassword);

**Comment by xMAnton** [comment]
Hello @ronaldomaya,

with which version of Zimbra have you tested it? I haven't update ADPassword for a while because Zimbra is not used in my current organization.

However, feel free to fork the code and then send a PR. 

Thank you,
A.
